stages:
  - test
  - test-manual

.test-windows:
    stage: "test"
    variables:
      PYTHON_VERSION: "3.8"
      UV_LINK_MODE: copy
    script:
      - uv venv --python $PYTHON_VERSION
      - uv pip install .
      - uv pip install pytest
      - .venv\Scripts\activate
      - pytest
    tags:
      - windows
      - $PYTHON_VERSION

.test-windows-manual:
    extends: ".test-windows"
    stage: "test-manual"
    when: manual

.test-debian:
    stage: "test"
    image: ghcr.io/astral-sh/uv:debian-slim
    script:
      - uv venv --python $PYTHON_VERSION
      - uv pip install .
      - uv pip install pytest
      - source .venv/bin/activate
      - pytest
    tags:
      - debian
      - $PYTHON_VERSION

.test-debian-manual:
    extends: ".test-debian"
    stage: "test-manual"
    when: manual

test-debian-3.8:
    extends: ".test-debian-manual"
    variables:
      PYTHON_VERSION: "3.8"
      UV_LINK_MODE: copy

test-debian-3.9:
    extends: ".test-debian-manual"
    variables:
      PYTHON_VERSION: "3.9"
      UV_LINK_MODE: copy

test-debian-3.10:
    extends: ".test-debian-manual"
    variables:
      PYTHON_VERSION: "3.10"
      UV_LINK_MODE: copy

test-debian-3.11:
    extends: ".test-debian-manual"
    variables:
      PYTHON_VERSION: "3.11"
      UV_LINK_MODE: copy

test-debian-3.12:
    extends: ".test-debian"
    variables:
      PYTHON_VERSION: "3.12"
      UV_LINK_MODE: copy

test-windows-3.8:
    extends: ".test-windows-manual"
    variables:
      PYTHON_VERSION: "3.8"
      UV_LINK_MODE: copy

test-windows-3.9:
    extends: ".test-windows-manual"
    variables:
      PYTHON_VERSION: "3.9"
      UV_LINK_MODE: copy

test-windows-3.10:
    extends: ".test-windows-manual"
    variables:
      PYTHON_VERSION: "3.10"
      UV_LINK_MODE: copy

test-windows-3.11:
    extends: ".test-windows-manual"
    variables:
      PYTHON_VERSION: "3.11"
      UV_LINK_MODE: copy

test-windows-3.12:
    extends: ".test-windows"
    variables:
      PYTHON_VERSION: "3.12"
      UV_LINK_MODE: copy
