# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: mopeds

theme:
  name: material
  custom_dir: overrides
  features:
    - content.action.edit

nav:
  - Home: index.md
  - Simulation NLE: Simulation NLE.ipynb
  - Parameter Estimation NLE: Parameter Estimation NLE.ipynb
  - OED NLE: Optimal Experimental Design NLE.ipynb
  - Simulation DAE: Simulation DAE.ipynb
  - PE DAE: Parameter Estimation DAE.ipynb
  - OED DAE: Optimal Experimental Design DAE.ipynb

repo_url: https://git.tu-berlin.de/dbta/optimization/mopeds

edit_uri: edit/main/docs/

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

plugins:
  - mkdocs-jupyter:
      ignore: [".ipynb_checkpoints/*.ipynb"]
