# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: mopeds

theme:
  name: material
  custom_dir: overrides

nav:
  - Home: index.md
  - Simulation NLE: Simulation NLE.ipynb
  - Parameter Estimation NLE: Parameter Estimation NLE.ipynb
  - OED NLE: Optimal Experimental Design NLE.ipynb

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

plugins:
  - mkdocs-jupyter:
      ignore: [".ipynb_checkpoints/*.ipynb"]
