[tool.poetry]
requires-poetry = '>=2.0,<3.0'

[tool.poetry.group.test.dependencies]
pytest = "*"

[tool.poetry.group.docs.dependencies]
notebook = "*"

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"


[project]
name = "mopeds"
description = "Simulate and Optimize (Parameter Estimation, Optimal Experimental Design) NLE, ODE and DAE"
license = "MIT"
version = "0.10.2"
readme = "README.md"
authors = [{name = "Volodymyr Kozachynskyi", email = "vovakozach@gmail.com"}]
requires-python = '>=3.8,<3.13'
dependencies = ['casadi (<3.7.0)', 'numpy', 'scipy', 'matplotlib', 'pandas', 'tqdm']

[project.urls]
homepage = "https://mopeds.readthedocs.io/en/latest/"
repository = "https://git.tu-berlin.de/dbta/optimization/mopeds"
