# Tox configuration file
# Read more under https://tox.readthedocs.org/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

[tox]
isolated_build = true
envlist = py37

[testenv]
whitelist_externals = poetry
commands =
    poetry install -v
    poetry run pytest tests/
