import copy
from datetime import datetime, timedelta

import casadi as ca
import matplotlib.cm as cm
import numpy as np
from matplotlib import pyplot as plt

import par_est
from par_est.simulation import SimulatorNLE


def initialize_problem():

    variable_list = par_est.VariableList()

    # fmt: off 
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe1_i0", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe1_i3", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe2_i0", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe2_i3", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe3_i0", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe3_i3", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe4_i0", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe4_i3", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe5_i0", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe5_i3", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe6_i0", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe6_i3", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe7_i0", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe1_i1", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe1_i2", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe1_i3", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe2_i1", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe2_i2", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe2_i3", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe3_i1", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe3_i2", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe3_i3", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe4_i1", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe4_i2", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe4_i3", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe5_i1", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe5_i2", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe5_i3", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe6_i1", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe6_i2", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe6_i3", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe1_i1", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe1_i2", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe2_i1", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe2_i2", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe3_i1", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe3_i2", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe4_i1", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe4_i2", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe5_i1", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe5_i2", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe6_i1", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_A_fe6_i2", 8.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe1_i1", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe1_i2", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe1_i3", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe2_i1", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe2_i2", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe2_i3", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe3_i1", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe3_i2", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe3_i3", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe4_i1", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe4_i2", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe4_i3", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe5_i1", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe5_i2", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe5_i3", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe6_i1", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe6_i2", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe6_i3", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe1_i0", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe2_i0", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe3_i0", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe4_i0", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe5_i0", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe6_i0", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_B_fe7_i0", 20.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe1_i0", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe1_i3", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe2_i0", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe2_i3", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe3_i0", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe3_i3", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe4_i0", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe4_i3", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe5_i0", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe5_i3", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe6_i0", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe6_i3", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe7_i0", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe1_i1", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe1_i2", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe2_i1", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe2_i2", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe3_i1", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe3_i2", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe4_i1", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe4_i2", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe5_i1", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe5_i2", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe6_i1", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_c_C_fe6_i2", 0.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe1_i0", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe2_i0", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe3_i0", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe4_i0", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe5_i0", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe6_i0", 333.0))
    variable_list.add_variable(par_est.VariableAlgebraic("e0_T_fe7_i0", 333.0))
    variable_list.add_variable(par_est.VariableParameter("e0_dldgreek_tau_i2_j1", 1.167839841902244))
    variable_list.add_variable(par_est.VariableParameter("e0_dldgreek_tau_i2_j2", 0.775254648382856))
    variable_list.add_variable(par_est.VariableParameter("e0_dldgreek_tau_i2_j3", -7.531972331053937))
    variable_list.add_variable(par_est.VariableParameter("e0_dldgreek_tau_i3_j1", -0.253197259961796))
    variable_list.add_variable(par_est.VariableParameter("e0_dldgreek_tau_i3_j2", 1.053197461577804))
    variable_list.add_variable(par_est.VariableParameter("e0_greek_Deltat", 600.0))
    variable_list.add_variable(par_est.VariableParameter("e0_V", 1.0))
    variable_list.add_variable(par_est.VariableParameter("e0_E_A", 69000.0))
    variable_list.add_variable(par_est.VariableParameter("e0_E_B", 72000.0))
    variable_list.add_variable(par_est.VariableParameter("e0_F", 6.5E-4))
    variable_list.add_variable(par_est.VariableParameter("e0_R", 8.314))
    variable_list.add_variable(par_est.VariableParameter("e0_greek_rho", 800.0))
    variable_list.add_variable(par_est.VariableParameter("e0_H_A", 45000.0))
    variable_list.add_variable(par_est.VariableParameter("e0_H_B", -55000.0))
    variable_list.add_variable(par_est.VariableParameter("e0_T_Cool", 333.0))
    variable_list.add_variable(par_est.VariableParameter("e0_T_In", 333.0))
    variable_list.add_variable(par_est.VariableParameter("e0_UA", 1.4))
    variable_list.add_variable(par_est.VariableParameter("e0_cp", 3.5))
    variable_list.add_variable(par_est.VariableParameter("e0_c_B0", 15.0))
    variable_list.add_variable(par_est.VariableParameter("e0_dldgreek_tau_i0_j2", 1.739387967160278))
    variable_list.add_variable(par_est.VariableParameter("e0_dldgreek_tau_i0_j3", -3.000000252020032))
    variable_list.add_variable(par_est.VariableParameter("e0_x_Init_x3", 0.0))
    variable_list.add_variable(par_est.VariableParameter("e0_dldgreek_tau_i1_j1", 3.224746191683931))
    variable_list.add_variable(par_est.VariableParameter("e0_c_A0", 5.0))
    variable_list.add_variable(par_est.VariableParameter("e0_dldgreek_tau_i1_j2", -3.567840077120938))
    variable_list.add_variable(par_est.VariableParameter("e0_dldgreek_tau_i1_j3", 5.53197241506063))
    variable_list.add_variable(par_est.VariableParameter("e0_dldgreek_tau_i0_j1", -4.139388773624379))
    variable_list.add_variable(par_est.VariableParameter("e0_c_C0", 0.0))
    variable_list.add_variable(par_est.VariableParameter("e0_x_Init_x1", 8.0))
    variable_list.add_variable(par_est.VariableParameter("e0_x_Init_x4", 333.0))
    variable_list.add_variable(par_est.VariableParameter("e0_dldgreek_tau_i3_j3", 5.00000016801334))
    variable_list.add_variable(par_est.VariableParameter("e0_k_A", 5000000.0))
    variable_list.add_variable(par_est.VariableParameter("e0_k_B", 1.0E7))
    variable_list.add_variable(par_est.VariableParameter("e0_x_Init_x2", 20.0))

    m = par_est.Model(variable_list)

    dydx1 = 	 m.varlist_all['e0_c_A_fe1_i0'].casadi_var - ( m.varlist_all['e0_x_Init_x1'].casadi_var ) 

    dydx2 = 	 m.varlist_all['e0_c_A_fe1_i3'].casadi_var - ( m.varlist_all['e0_c_A_fe2_i0'].casadi_var ) 

    dydx3 = 	 m.varlist_all['e0_c_A_fe2_i3'].casadi_var - ( m.varlist_all['e0_c_A_fe3_i0'].casadi_var ) 

    dydx4 = 	 m.varlist_all['e0_c_A_fe3_i3'].casadi_var - ( m.varlist_all['e0_c_A_fe4_i0'].casadi_var ) 

    dydx5 = 	 m.varlist_all['e0_c_A_fe4_i3'].casadi_var - ( m.varlist_all['e0_c_A_fe5_i0'].casadi_var ) 

    dydx6 = 	 m.varlist_all['e0_c_A_fe5_i3'].casadi_var - ( m.varlist_all['e0_c_A_fe6_i0'].casadi_var ) 

    dydx7 = 	 m.varlist_all['e0_c_A_fe6_i3'].casadi_var - ( m.varlist_all['e0_c_A_fe7_i0'].casadi_var ) 

    dydx8 = 	 ( m.varlist_all['e0_c_A_fe1_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_A_fe1_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_A_fe1_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_A_fe1_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe1_i1'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe1_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i1'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe1_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i1'].casadi_var ) ) ) 

    dydx9 = 	 ( m.varlist_all['e0_c_A_fe1_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_A_fe1_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_A_fe1_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_A_fe1_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe1_i2'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe1_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i2'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe1_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i2'].casadi_var ) ) ) 

    dydx10 = 	 ( m.varlist_all['e0_c_A_fe1_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_A_fe1_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_A_fe1_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_A_fe1_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe1_i3'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe1_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i3'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe1_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i3'].casadi_var ) ) ) 

    dydx11 = 	 ( m.varlist_all['e0_c_A_fe2_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_A_fe2_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_A_fe2_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_A_fe2_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe2_i1'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe2_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i1'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe2_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i1'].casadi_var ) ) ) 

    dydx12 = 	 ( m.varlist_all['e0_c_A_fe2_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_A_fe2_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_A_fe2_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_A_fe2_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe2_i2'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe2_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i2'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe2_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i2'].casadi_var ) ) ) 

    dydx13 = 	 ( m.varlist_all['e0_c_A_fe2_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_A_fe2_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_A_fe2_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_A_fe2_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe2_i3'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe2_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i3'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe2_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i3'].casadi_var ) ) ) 

    dydx14 = 	 ( m.varlist_all['e0_c_A_fe3_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_A_fe3_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_A_fe3_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_A_fe3_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe3_i1'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe3_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i1'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe3_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i1'].casadi_var ) ) ) 

    dydx15 = 	 ( m.varlist_all['e0_c_A_fe3_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_A_fe3_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_A_fe3_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_A_fe3_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe3_i2'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe3_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i2'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe3_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i2'].casadi_var ) ) ) 

    dydx16 = 	 ( m.varlist_all['e0_c_A_fe3_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_A_fe3_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_A_fe3_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_A_fe3_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe3_i3'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe3_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i3'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe3_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i3'].casadi_var ) ) ) 

    dydx17 = 	 ( m.varlist_all['e0_c_A_fe4_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_A_fe4_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_A_fe4_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_A_fe4_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe4_i1'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe4_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i1'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe4_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i1'].casadi_var ) ) ) 

    dydx18 = 	 ( m.varlist_all['e0_c_A_fe4_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_A_fe4_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_A_fe4_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_A_fe4_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe4_i2'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe4_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i2'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe4_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i2'].casadi_var ) ) ) 

    dydx19 = 	 ( m.varlist_all['e0_c_A_fe4_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_A_fe4_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_A_fe4_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_A_fe4_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe4_i3'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe4_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i3'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe4_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i3'].casadi_var ) ) ) 

    dydx20 = 	 ( m.varlist_all['e0_c_A_fe5_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_A_fe5_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_A_fe5_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_A_fe5_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe5_i1'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe5_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i1'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe5_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i1'].casadi_var ) ) ) 

    dydx21 = 	 ( m.varlist_all['e0_c_A_fe5_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_A_fe5_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_A_fe5_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_A_fe5_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe5_i2'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe5_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i2'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe5_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i2'].casadi_var ) ) ) 

    dydx22 = 	 ( m.varlist_all['e0_c_A_fe5_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_A_fe5_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_A_fe5_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_A_fe5_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe5_i3'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe5_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i3'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe5_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i3'].casadi_var ) ) ) 

    dydx23 = 	 ( m.varlist_all['e0_c_A_fe6_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_A_fe6_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_A_fe6_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_A_fe6_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe6_i1'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe6_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i1'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe6_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i1'].casadi_var ) ) ) 

    dydx24 = 	 ( m.varlist_all['e0_c_A_fe6_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_A_fe6_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_A_fe6_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_A_fe6_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe6_i2'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe6_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i2'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe6_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i2'].casadi_var ) ) ) 

    dydx25 = 	 ( m.varlist_all['e0_c_A_fe6_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_A_fe6_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_A_fe6_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_A_fe6_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_A0'].casadi_var - m.varlist_all['e0_c_A_fe6_i3'].casadi_var ) - m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe6_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i3'].casadi_var ) ) + m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe6_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i3'].casadi_var ) ) ) 

    dydx26 = 	 m.varlist_all['e0_c_B_fe1_i0'].casadi_var - ( m.varlist_all['e0_x_Init_x2'].casadi_var ) 

    dydx27 = 	 m.varlist_all['e0_c_B_fe1_i3'].casadi_var - ( m.varlist_all['e0_c_B_fe2_i0'].casadi_var ) 

    dydx28 = 	 m.varlist_all['e0_c_B_fe2_i3'].casadi_var - ( m.varlist_all['e0_c_B_fe3_i0'].casadi_var ) 

    dydx29 = 	 m.varlist_all['e0_c_B_fe3_i3'].casadi_var - ( m.varlist_all['e0_c_B_fe4_i0'].casadi_var ) 

    dydx30 = 	 m.varlist_all['e0_c_B_fe4_i3'].casadi_var - ( m.varlist_all['e0_c_B_fe5_i0'].casadi_var ) 

    dydx31 = 	 m.varlist_all['e0_c_B_fe5_i3'].casadi_var - ( m.varlist_all['e0_c_B_fe6_i0'].casadi_var ) 

    dydx32 = 	 m.varlist_all['e0_c_B_fe6_i3'].casadi_var - ( m.varlist_all['e0_c_B_fe7_i0'].casadi_var ) 

    dydx33 = 	 ( m.varlist_all['e0_c_B_fe1_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_B_fe1_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_B_fe1_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_B_fe1_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe1_i1'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe1_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i1'].casadi_var ) ) ) 

    dydx34 = 	 ( m.varlist_all['e0_c_B_fe1_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_B_fe1_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_B_fe1_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_B_fe1_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe1_i2'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe1_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i2'].casadi_var ) ) ) 

    dydx35 = 	 ( m.varlist_all['e0_c_B_fe1_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_B_fe1_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_B_fe1_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_B_fe1_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe1_i3'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe1_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i3'].casadi_var ) ) ) 

    dydx36 = 	 ( m.varlist_all['e0_c_B_fe2_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_B_fe2_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_B_fe2_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_B_fe2_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe2_i1'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe2_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i1'].casadi_var ) ) ) 

    dydx37 = 	 ( m.varlist_all['e0_c_B_fe2_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_B_fe2_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_B_fe2_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_B_fe2_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe2_i2'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe2_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i2'].casadi_var ) ) ) 

    dydx38 = 	 ( m.varlist_all['e0_c_B_fe2_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_B_fe2_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_B_fe2_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_B_fe2_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe2_i3'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe2_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i3'].casadi_var ) ) ) 

    dydx39 = 	 ( m.varlist_all['e0_c_B_fe3_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_B_fe3_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_B_fe3_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_B_fe3_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe3_i1'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe3_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i1'].casadi_var ) ) ) 

    dydx40 = 	 ( m.varlist_all['e0_c_B_fe3_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_B_fe3_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_B_fe3_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_B_fe3_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe3_i2'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe3_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i2'].casadi_var ) ) ) 

    dydx41 = 	 ( m.varlist_all['e0_c_B_fe3_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_B_fe3_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_B_fe3_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_B_fe3_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe3_i3'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe3_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i3'].casadi_var ) ) ) 

    dydx42 = 	 ( m.varlist_all['e0_c_B_fe4_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_B_fe4_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_B_fe4_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_B_fe4_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe4_i1'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe4_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i1'].casadi_var ) ) ) 

    dydx43 = 	 ( m.varlist_all['e0_c_B_fe4_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_B_fe4_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_B_fe4_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_B_fe4_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe4_i2'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe4_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i2'].casadi_var ) ) ) 

    dydx44 = 	 ( m.varlist_all['e0_c_B_fe4_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_B_fe4_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_B_fe4_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_B_fe4_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe4_i3'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe4_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i3'].casadi_var ) ) ) 

    dydx45 = 	 ( m.varlist_all['e0_c_B_fe5_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_B_fe5_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_B_fe5_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_B_fe5_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe5_i1'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe5_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i1'].casadi_var ) ) ) 

    dydx46 = 	 ( m.varlist_all['e0_c_B_fe5_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_B_fe5_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_B_fe5_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_B_fe5_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe5_i2'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe5_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i2'].casadi_var ) ) ) 

    dydx47 = 	 ( m.varlist_all['e0_c_B_fe5_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_B_fe5_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_B_fe5_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_B_fe5_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe5_i3'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe5_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i3'].casadi_var ) ) ) 

    dydx48 = 	 ( m.varlist_all['e0_c_B_fe6_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_B_fe6_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_B_fe6_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_B_fe6_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe6_i1'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe6_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i1'].casadi_var ) ) ) 

    dydx49 = 	 ( m.varlist_all['e0_c_B_fe6_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_B_fe6_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_B_fe6_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_B_fe6_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe6_i2'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe6_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i2'].casadi_var ) ) ) 

    dydx50 = 	 ( m.varlist_all['e0_c_B_fe6_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_B_fe6_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_B_fe6_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_B_fe6_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_B0'].casadi_var - m.varlist_all['e0_c_B_fe6_i3'].casadi_var ) - m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe6_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i3'].casadi_var ) ) ) 

    dydx51 = 	 m.varlist_all['e0_c_C_fe1_i0'].casadi_var - ( m.varlist_all['e0_x_Init_x3'].casadi_var ) 

    dydx52 = 	 m.varlist_all['e0_c_C_fe1_i3'].casadi_var - ( m.varlist_all['e0_c_C_fe2_i0'].casadi_var ) 

    dydx53 = 	 m.varlist_all['e0_c_C_fe2_i3'].casadi_var - ( m.varlist_all['e0_c_C_fe3_i0'].casadi_var ) 

    dydx54 = 	 m.varlist_all['e0_c_C_fe3_i3'].casadi_var - ( m.varlist_all['e0_c_C_fe4_i0'].casadi_var ) 

    dydx55 = 	 m.varlist_all['e0_c_C_fe4_i3'].casadi_var - ( m.varlist_all['e0_c_C_fe5_i0'].casadi_var ) 

    dydx56 = 	 m.varlist_all['e0_c_C_fe5_i3'].casadi_var - ( m.varlist_all['e0_c_C_fe6_i0'].casadi_var ) 

    dydx57 = 	 m.varlist_all['e0_c_C_fe6_i3'].casadi_var - ( m.varlist_all['e0_c_C_fe7_i0'].casadi_var ) 

    dydx58 = 	 ( m.varlist_all['e0_c_C_fe1_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_C_fe1_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_C_fe1_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_C_fe1_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe1_i1'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe1_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i1'].casadi_var ) ) ) 

    dydx59 = 	 ( m.varlist_all['e0_c_C_fe1_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_C_fe1_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_C_fe1_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_C_fe1_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe1_i2'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe1_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i2'].casadi_var ) ) ) 

    dydx60 = 	 ( m.varlist_all['e0_c_C_fe1_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_C_fe1_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_C_fe1_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_C_fe1_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe1_i3'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe1_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i3'].casadi_var ) ) ) 

    dydx61 = 	 ( m.varlist_all['e0_c_C_fe2_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_C_fe2_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_C_fe2_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_C_fe2_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe2_i1'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe2_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i1'].casadi_var ) ) ) 

    dydx62 = 	 ( m.varlist_all['e0_c_C_fe2_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_C_fe2_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_C_fe2_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_C_fe2_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe2_i2'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe2_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i2'].casadi_var ) ) ) 

    dydx63 = 	 ( m.varlist_all['e0_c_C_fe2_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_C_fe2_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_C_fe2_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_C_fe2_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe2_i3'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe2_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i3'].casadi_var ) ) ) 

    dydx64 = 	 ( m.varlist_all['e0_c_C_fe3_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_C_fe3_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_C_fe3_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_C_fe3_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe3_i1'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe3_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i1'].casadi_var ) ) ) 

    dydx65 = 	 ( m.varlist_all['e0_c_C_fe3_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_C_fe3_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_C_fe3_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_C_fe3_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe3_i2'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe3_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i2'].casadi_var ) ) ) 

    dydx66 = 	 ( m.varlist_all['e0_c_C_fe3_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_C_fe3_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_C_fe3_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_C_fe3_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe3_i3'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe3_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i3'].casadi_var ) ) ) 

    dydx67 = 	 ( m.varlist_all['e0_c_C_fe4_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_C_fe4_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_C_fe4_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_C_fe4_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe4_i1'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe4_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i1'].casadi_var ) ) ) 

    dydx68 = 	 ( m.varlist_all['e0_c_C_fe4_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_C_fe4_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_C_fe4_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_C_fe4_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe4_i2'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe4_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i2'].casadi_var ) ) ) 

    dydx69 = 	 ( m.varlist_all['e0_c_C_fe4_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_C_fe4_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_C_fe4_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_C_fe4_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe4_i3'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe4_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i3'].casadi_var ) ) ) 

    dydx70 = 	 ( m.varlist_all['e0_c_C_fe5_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_C_fe5_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_C_fe5_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_C_fe5_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe5_i1'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe5_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i1'].casadi_var ) ) ) 

    dydx71 = 	 ( m.varlist_all['e0_c_C_fe5_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_C_fe5_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_C_fe5_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_C_fe5_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe5_i2'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe5_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i2'].casadi_var ) ) ) 

    dydx72 = 	 ( m.varlist_all['e0_c_C_fe5_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_C_fe5_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_C_fe5_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_C_fe5_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe5_i3'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe5_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i3'].casadi_var ) ) ) 

    dydx73 = 	 ( m.varlist_all['e0_c_C_fe6_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_c_C_fe6_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_c_C_fe6_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_c_C_fe6_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe6_i1'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe6_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i1'].casadi_var ) ) ) 

    dydx74 = 	 ( m.varlist_all['e0_c_C_fe6_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_c_C_fe6_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_c_C_fe6_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_c_C_fe6_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe6_i2'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe6_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i2'].casadi_var ) ) ) 

    dydx75 = 	 ( m.varlist_all['e0_c_C_fe6_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_c_C_fe6_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_c_C_fe6_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_c_C_fe6_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_c_C0'].casadi_var - m.varlist_all['e0_c_C_fe6_i3'].casadi_var ) + m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe6_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i3'].casadi_var ) ) ) 

    dydx76 = 	 m.varlist_all['e0_T_fe1_i0'].casadi_var - ( m.varlist_all['e0_x_Init_x4'].casadi_var ) 

    dydx77 = 	 m.varlist_all['e0_T_fe1_i3'].casadi_var - ( m.varlist_all['e0_T_fe2_i0'].casadi_var ) 

    dydx78 = 	 m.varlist_all['e0_T_fe2_i3'].casadi_var - ( m.varlist_all['e0_T_fe3_i0'].casadi_var ) 

    dydx79 = 	 m.varlist_all['e0_T_fe3_i3'].casadi_var - ( m.varlist_all['e0_T_fe4_i0'].casadi_var ) 

    dydx80 = 	 m.varlist_all['e0_T_fe4_i3'].casadi_var - ( m.varlist_all['e0_T_fe5_i0'].casadi_var ) 

    dydx81 = 	 m.varlist_all['e0_T_fe5_i3'].casadi_var - ( m.varlist_all['e0_T_fe6_i0'].casadi_var ) 

    dydx82 = 	 m.varlist_all['e0_T_fe6_i3'].casadi_var - ( m.varlist_all['e0_T_fe7_i0'].casadi_var ) 

    dydx83 = 	 ( m.varlist_all['e0_T_fe1_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_T_fe1_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_T_fe1_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_T_fe1_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe1_i1'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe1_i1'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe1_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i1'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe1_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i1'].casadi_var ) ) ) 

    dydx84 = 	 ( m.varlist_all['e0_T_fe1_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_T_fe1_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_T_fe1_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_T_fe1_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe1_i2'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe1_i2'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe1_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i2'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe1_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i2'].casadi_var ) ) ) 

    dydx85 = 	 ( m.varlist_all['e0_T_fe1_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_T_fe1_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_T_fe1_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_T_fe1_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe1_i3'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe1_i3'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe1_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i3'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe1_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe1_i3'].casadi_var ) ) ) 

    dydx86 = 	 ( m.varlist_all['e0_T_fe2_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_T_fe2_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_T_fe2_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_T_fe2_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe2_i1'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe2_i1'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe2_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i1'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe2_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i1'].casadi_var ) ) ) 

    dydx87 = 	 ( m.varlist_all['e0_T_fe2_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_T_fe2_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_T_fe2_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_T_fe2_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe2_i2'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe2_i2'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe2_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i2'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe2_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i2'].casadi_var ) ) ) 

    dydx88 = 	 ( m.varlist_all['e0_T_fe2_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_T_fe2_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_T_fe2_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_T_fe2_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe2_i3'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe2_i3'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe2_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i3'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe2_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe2_i3'].casadi_var ) ) ) 

    dydx89 = 	 ( m.varlist_all['e0_T_fe3_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_T_fe3_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_T_fe3_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_T_fe3_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe3_i1'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe3_i1'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe3_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i1'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe3_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i1'].casadi_var ) ) ) 

    dydx90 = 	 ( m.varlist_all['e0_T_fe3_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_T_fe3_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_T_fe3_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_T_fe3_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe3_i2'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe3_i2'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe3_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i2'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe3_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i2'].casadi_var ) ) ) 

    dydx91 = 	 ( m.varlist_all['e0_T_fe3_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_T_fe3_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_T_fe3_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_T_fe3_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe3_i3'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe3_i3'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe3_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i3'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe3_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe3_i3'].casadi_var ) ) ) 

    dydx92 = 	 ( m.varlist_all['e0_T_fe4_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_T_fe4_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_T_fe4_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_T_fe4_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe4_i1'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe4_i1'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe4_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i1'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe4_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i1'].casadi_var ) ) ) 

    dydx93 = 	 ( m.varlist_all['e0_T_fe4_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_T_fe4_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_T_fe4_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_T_fe4_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe4_i2'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe4_i2'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe4_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i2'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe4_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i2'].casadi_var ) ) ) 

    dydx94 = 	 ( m.varlist_all['e0_T_fe4_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_T_fe4_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_T_fe4_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_T_fe4_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe4_i3'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe4_i3'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe4_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i3'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe4_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe4_i3'].casadi_var ) ) ) 

    dydx95 = 	 ( m.varlist_all['e0_T_fe5_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_T_fe5_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_T_fe5_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_T_fe5_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe5_i1'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe5_i1'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe5_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i1'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe5_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i1'].casadi_var ) ) ) 

    dydx96 = 	 ( m.varlist_all['e0_T_fe5_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_T_fe5_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_T_fe5_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_T_fe5_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe5_i2'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe5_i2'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe5_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i2'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe5_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i2'].casadi_var ) ) ) 

    dydx97 = 	 ( m.varlist_all['e0_T_fe5_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_T_fe5_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_T_fe5_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_T_fe5_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe5_i3'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe5_i3'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe5_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i3'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe5_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe5_i3'].casadi_var ) ) ) 

    dydx98 = 	 ( m.varlist_all['e0_T_fe6_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j1'].casadi_var + m.varlist_all['e0_T_fe6_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j1'].casadi_var + m.varlist_all['e0_T_fe6_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j1'].casadi_var + m.varlist_all['e0_T_fe6_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j1'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe6_i1'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe6_i1'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe6_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i1'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe6_i1'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i1'].casadi_var ) ) ) 

    dydx99 = 	 ( m.varlist_all['e0_T_fe6_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j2'].casadi_var + m.varlist_all['e0_T_fe6_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j2'].casadi_var + m.varlist_all['e0_T_fe6_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j2'].casadi_var + m.varlist_all['e0_T_fe6_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j2'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe6_i2'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe6_i2'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe6_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i2'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe6_i2'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i2'].casadi_var ) ) ) 

    dydx100 = 	 ( m.varlist_all['e0_T_fe6_i0'].casadi_var * m.varlist_all['e0_dldgreek_tau_i0_j3'].casadi_var + m.varlist_all['e0_T_fe6_i1'].casadi_var * m.varlist_all['e0_dldgreek_tau_i1_j3'].casadi_var + m.varlist_all['e0_T_fe6_i2'].casadi_var * m.varlist_all['e0_dldgreek_tau_i2_j3'].casadi_var + m.varlist_all['e0_T_fe6_i3'].casadi_var * m.varlist_all['e0_dldgreek_tau_i3_j3'].casadi_var ) * ( 1.0 )/( m.varlist_all['e0_greek_Deltat'].casadi_var ) - ( ( m.varlist_all['e0_F'].casadi_var )/( m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_In'].casadi_var - m.varlist_all['e0_T_fe6_i3'].casadi_var ) + ( m.varlist_all['e0_UA'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var * m.varlist_all['e0_V'].casadi_var ) * ( m.varlist_all['e0_T_Cool'].casadi_var - m.varlist_all['e0_T_fe6_i3'].casadi_var ) + (  - m.varlist_all['e0_H_A'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_A'].casadi_var * m.varlist_all['e0_c_A_fe6_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_A'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i3'].casadi_var ) ) + (  - m.varlist_all['e0_H_B'].casadi_var )/( m.varlist_all['e0_greek_rho'].casadi_var * m.varlist_all['e0_cp'].casadi_var ) * m.varlist_all['e0_k_B'].casadi_var * m.varlist_all['e0_c_B_fe6_i3'].casadi_var * ca.exp( (  - m.varlist_all['e0_E_B'].casadi_var )/( m.varlist_all['e0_R'].casadi_var * m.varlist_all['e0_T_fe6_i3'].casadi_var ) ) ) 


    # fmt: on"

    m.add_equations_algebraic([dydx1 ,dydx2 ,dydx3 ,dydx4 ,dydx5 ,dydx6 ,dydx7 ,dydx8 ,dydx9 ,dydx10 ,dydx11 ,dydx12 ,dydx13 ,dydx14 ,dydx15 ,dydx16 ,dydx17 ,dydx18 ,dydx19 ,dydx20 ,dydx21 ,dydx22 ,dydx23 ,dydx24 ,dydx25 ,dydx26 ,dydx27 ,dydx28 ,dydx29 ,dydx30 ,dydx31 ,dydx32 ,dydx33 ,dydx34 ,dydx35 ,dydx36 ,dydx37 ,dydx38 ,dydx39 ,dydx40 ,dydx41 ,dydx42 ,dydx43 ,dydx44 ,dydx45 ,dydx46 ,dydx47 ,dydx48 ,dydx49 ,dydx50 ,dydx51 ,dydx52 ,dydx53 ,dydx54 ,dydx55 ,dydx56 ,dydx57 ,dydx58 ,dydx59 ,dydx60 ,dydx61 ,dydx62 ,dydx63 ,dydx64 ,dydx65 ,dydx66 ,dydx67 ,dydx68 ,dydx69 ,dydx70 ,dydx71 ,dydx72 ,dydx73 ,dydx74 ,dydx75 ,dydx76 ,dydx77 ,dydx78 ,dydx79 ,dydx80 ,dydx81 ,dydx82 ,dydx83 ,dydx84 ,dydx85 ,dydx86 ,dydx87 ,dydx88 ,dydx89 ,dydx90 ,dydx91 ,dydx92 ,dydx93 ,dydx94 ,dydx95 ,dydx96 ,dydx97 ,dydx98 ,dydx99 ,dydx100 ,])

    return variable_list, m

if __name__ == "__main__":

    variable_list, m = initialize_problem()

    # Set parameters and controls to fixed state so their values are used for simulation
    var_list_fixed = copy.deepcopy(variable_list)
    for var in var_list_fixed.values():
        var.fixed = True

    # Create simulation Object
    sim_fixed = SimulatorNLE(m, var_list_fixed)
    # Run simulation and get simple results as array of numbers, but information about state variables and timestamp is lost
    res_simple = sim_fixed.simulate_sym()
    # Run simulation and connect results with actual state variables, which can be plotted based on available data
    res = sim_fixed.generate_exp_data()
    Val_Res = res_simple['r']

    Time = np.array([0, 600, 1200, 1800, 2400, 3000, 3600])
    Val_dict = {"C_A":Val_Res[0:13:2], "C_B": Val_Res[61:68:1], "C_C": Val_Res[68:81:2], "T": Val_Res[93:100:1]}

    figure, axes_array = plt.subplots(len(Val_dict))
    for var, ax in zip(Val_dict, axes_array):
        print(Val_dict[var])
        ax.plot(Time, Val_dict[var], label=var)
        ax.legend()
    plt.show()